name: features_{{feature_name.snakeCase()}}
description: "This package provides {{feature_name.snakeCase()}} features."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.1.0

flutter:
